BikeMgr.Web/Models/Bike.cs
using System.ComponentModel.DataAnnotations;

namespace BikeMgrWeb.Models
{
    public class Bike
    {
        public int ID { get; set; }
        [Required]
        [StringLength(200)]
        [Display(Name = "Model Name")]
        public string Name { get; set; }
        [Required]
        [StringLength(200)]
        public string Brand { get; set; }
        [Required]
        [Display(Name = "No of Wheels")]
        public int? Wheels { get; set; }
        [Required]
        [StringLength(200)]
        [Display(Name = "Frame Material")]
        public string FrameMaterial { get; set; }
        [Required]
        [Display(Name = "Type")]
        public virtual BikeType BikeType { get; set; }
        [Required]
        [DisplayFormat(DataFormatString = "{0:C}")]
        public decimal Price { get; set; }
        [StringLength(500)]
        public string ImageLocation { get; set; }
    }
}

BikeMgr.Web/Models/BikeType.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BikeMgrWeb.Models
{
    [Table(@"BikeType")]
    public class BikeType
    {
        [Key]
        public int ID { get; set; }
        [StringLength(200)]
        public string TypeName { get; set; }
    }
}

BikeMgr.Web/Controllers/BikeController.cs
using BikeMgrWeb.DTO;
using BikeMgrWeb.Loggers;
using BikeMgrWeb.Models;
using BikeMgrWeb.Services;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Net;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Thinktecture.IdentityModel.Mvc;

namespace BikeMgrWeb.Controllers
{
    [ResourceAuthorize("Read", "Generic")]
    public class BikeController : Controller
    {
        private readonly HttpService _http;
        private readonly ILogService _log;

        private static string ApiUri = ConfigurationManager.AppSettings["BikeApi.Uri"];

        public BikeController(HttpService http, ILogService log)
        {
            _http = http;
            _log = log;
        }

        [HttpGet]
        public async Task<ActionResult> Index(string alertMsg = null, string sortOrder = null, string currentFilter = null, string search = null, int? page = null)
        {
            ViewBag.AlertMsg = alertMsg;
            if (search != null)
                page = 1;
            else 
            {
                search = currentFilter;
                if(String.IsNullOrEmpty(search) && HttpContext.Session["Bike.Search.search"] != null) search = HttpContext.Session["Bike.Search.search"].ToString();
            }
            if (String.IsNullOrEmpty(sortOrder) && HttpContext.Session["Bike.Search.sortOrder"] != null) sortOrder = HttpContext.Session["Bike.Search.sortOrder"].ToString();
            if (page == null && HttpContext.Session["Bike.Search.page"] != null) page = Convert.ToInt32(HttpContext.Session["Bike.Search.page"].ToString());
            try
            {
                var bikePage = await _http.Get<Page<Bike>>(HttpContext, $"/api/bike?sortOrder={sortOrder}&search={search}&page={page}&pageSize=10");
                BikeIndexView<Bike> bikeView = new BikeIndexView<Bike>(bikePage);
                bikeView.CurrentSort = sortOrder;
                bikeView.NameSort = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
                bikeView.BrandSort = sortOrder == "brand" ? "brand_desc" : "brand";
                bikeView.WheelSort = sortOrder == "wheel" ? "wheel_desc" : "wheel";
                bikeView.FrameSort = sortOrder == "frame" ? "frame_desc" : "frame";
                bikeView.TypeSort = sortOrder == "type" ? "type_desc" : "type";
                bikeView.PriceSort = sortOrder == "price" ? "price_desc" : "price";
                bikeView.CurrentFilter = search;
                HttpContext.Session["Bike.Search.sortOrder"] = sortOrder;
                HttpContext.Session["Bike.Search.search"] = search;
                HttpContext.Session["Bike.Search.page"] = page;
                return View(bikeView);
            }
            catch (Exception ex)
            {
                _log.LogError(ex, ex.Message);
                ViewBag.AlertMsg = "Error retrieving bikes.";
                return View(BikeIndexView<Bike>.Create(new List<Bike>(), 0, 0));
            }
        }

        [ResourceAuthorize("Write", "Generic")]
        [HttpGet]
        public async Task<ActionResult> Create()
        {
            BikeDetailView bikeView = new BikeDetailView();
            bikeView.BikeTypes = new SelectList(await GetBikeTypes(), "ID", "TypeName");
            return View(bikeView);
        }

        [ResourceAuthorize("Write", "Generic")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(Bike bike, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var content = new MultipartFormDataContent();
                    content.Add(new StringContent(bike.ID.ToString()), "id");
                    content.Add(new StringContent(bike.Name), "name");
                    content.Add(new StringContent(bike.Brand), "brand");
                    content.Add(new StringContent(bike.Wheels.ToString()), "wheels");
                    content.Add(new StringContent(bike.FrameMaterial), "framematerial");
                    content.Add(new StringContent(bike.BikeType.ID.ToString()), "biketypeid");
                    content.Add(new StringContent(bike.Price.ToString()), "price");
                    if (file != null)
                        content.Add(new StreamContent(file.InputStream), "image", file.FileName);
                    var response = await _http.Post<BikeDTO>(HttpContext, "/api/bike", content);
                    return RedirectToAction("Index", new { alertMsg = String.Format("Bike {0} created successfully.", bike.Name) });
                }
                catch (Exception ex)
                {
                    _log.LogError(ex, ex.Message);
                    ViewBag.SaveResult = "An error occured saving the bike. Contact the support team.";
                    BikeDetailView bikeView = new BikeDetailView();
                    bikeView.BikeTypes = new SelectList(await GetBikeTypes(), "ID", "TypeName");
                    return View(bikeView);
                }
            }
            else
            {
                BikeDetailView bikeView = new BikeDetailView();
                bikeView.BikeTypes = new SelectList(await GetBikeTypes(), "ID", "TypeName");
                return View(bikeView);
            }
        }

        [HttpGet]
        public async Task<ActionResult> Details(int id)
        {
            return await GetBikeByID(id);
        }

        [ResourceAuthorize("Write", "Generic")]
        [HttpGet]
        public async Task<ActionResult> Edit(int id)
        {
            return await GetBikeByID(id);
        }

        [ResourceAuthorize("Write", "Generic")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(Bike bike, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                if (bike.ID == 0) { return new HttpStatusCodeResult(HttpStatusCode.BadRequest); }
                try
                {
                    var content = new MultipartFormDataContent();
                    content.Add(new StringContent(bike.ID.ToString()), "id");
                    content.Add(new StringContent(bike.Name), "name");
                    content.Add(new StringContent(bike.Brand), "brand");
                    content.Add(new StringContent(bike.Wheels.ToString()), "wheels");
                    content.Add(new StringContent(bike.FrameMaterial), "framematerial");
                    content.Add(new StringContent(bike.BikeType.ID.ToString()), "biketypeid");
                    content.Add(new StringContent(bike.Price.ToString()), "price");
                    if(file != null)
                        content.Add(new StreamContent(file.InputStream), "image", file.FileName);
                    var response = await _http.Put<BikeDTO>(HttpContext, "/api/bike", content);
                    return RedirectToAction("Index", new { alertMsg = String.Format("Bike {0} updated successfully.", bike.Name) });
                }
                catch (Exception ex)
                {
                    _log.LogError(ex, ex.Message);
                    ViewBag.SaveResult = "An error occured saving the bike. Contact the support team.";
                    BikeDetailView bikeView = new BikeDetailView(bike);
                    bikeView.BikeTypes = new SelectList(await GetBikeTypes(), "ID", "TypeName");
                    return View(bikeView);
                }
            }
            else
            {
                BikeDetailView bikeView = new BikeDetailView(bike);
                bikeView.BikeTypes = new SelectList(await GetBikeTypes(), "ID", "TypeName");
                return View(bikeView);
            }
        }

        [ResourceAuthorize("Write", "Generic")]
        public async Task<ActionResult> Delete(int id)
        {
            string status = "Failed to delete bike";
            try
            {
                if (await _http.Delete(HttpContext, $"/api/bike/{id}"))
                    status = "Bike deleted successfully!";
            }
            catch (Exception ex)
            { _log.LogError(ex, ex.Message); }
            return RedirectToAction("Index", new { alertMsg = status });
        }

        private async Task<List<BikeType>> GetBikeTypes()
        {
            try
            { return await _http.Get<List<BikeType>>(HttpContext, "/api/biketype"); }
            catch (Exception ex)
            {
                _log.LogError(ex, ex.Message);
                return new List<BikeType>();
            }
        }

        private async Task<ActionResult> GetBikeByID(int id)
        {
            try
            {
                BikeDetailView bikeView = new BikeDetailView(await _http.Get<Bike>(HttpContext, $"/api/bike/{id}"));
                bikeView.BikeTypes = new SelectList(await GetBikeTypes(), "ID", "TypeName");
                if (!String.IsNullOrWhiteSpace(bikeView.ImageLocation)) bikeView.ImageLocation = ApiUri + bikeView.ImageLocation;
                if (Request.Path.Contains("Details"))
                    return View("Details", bikeView);
                else
                    return View("Edit", bikeView);
            }
            catch (Exception ex)
            {
                _log.LogError(ex, ex.Message);
                return RedirectToAction("Index", new { alertMsg = "Error retrieving bike." });
            }
        }

    }
}

BikeMgr.Web/Views/Bike/Create.cshtml
@model BikeMgrWeb.Models.BikeDetailView

@{
    ViewBag.Title = "Create a Bike";
    Layout = "~/Views/Shared/_LayoutDialog.cshtml";
}

<h2 class="mt-3">Create a Bike</h2>

@using (Html.BeginForm("Create", "Bike", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="row">
        <div class="col-md-3">
            <input type="submit" value="Save" class="btn btn-primary mb-2" />
            <a href="~/Bike" class="btn btn-secondary mb-2">Cancel</a>
        </div>
        <div class="col-md-9">
            <a href="~/Bike" class="btn btn-info">Back To List</a>
        </div>
    </div>

    if (!String.IsNullOrWhiteSpace(ViewBag.SaveResult))
    {
        <div class="alert alert-danger" role="alert">
            @ViewBag.SaveResult
        </div>
    }

    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-row mt-2">
        <div class="form-group col">
            @Html.LabelFor(model => model.Name)
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", @aria_label = "Model Name" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
        <div class="form-group col">
            @Html.LabelFor(model => model.Brand)
            @Html.EditorFor(model => model.Brand, new { htmlAttributes = new { @class = "form-control", @aria_label = "Brand" } })
            @Html.ValidationMessageFor(model => model.Brand, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-row">
        <div class="form-group col-md-2">
            @Html.LabelFor(model => model.Wheels)
            @Html.EditorFor(model => model.Wheels, new { htmlAttributes = new { @class = "form-control", @aria_label = "Number of wheels" } })
            @Html.ValidationMessageFor(model => model.Wheels, "", new { @class = "text-danger" })
        </div>
        <div class="form-group col-md-3">
            @Html.LabelFor(model => model.FrameMaterial)
            @Html.EditorFor(model => model.FrameMaterial, new { htmlAttributes = new { @class = "form-control", @aria_label = "Frame Material" } })
            @Html.ValidationMessageFor(model => model.FrameMaterial, "", new { @class = "text-danger" })
        </div>
        <div class="form-group col-md-3">
            @Html.LabelFor(model => model.BikeType, "BikeType")
            @Html.DropDownList("BikeType.ID", (IEnumerable<SelectListItem>)Model.BikeTypes, "Choose...", htmlAttributes: new { @class = "form-control", @required = "true", @aria_label = "Bike Type" })
            @Html.ValidationMessageFor(model => model.BikeType, "", new { @class = "text-danger" })
        </div>
        <div class="form-group col-md-2">
            @Html.LabelFor(model => model.Price)
            @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control", @aria_label = "Price" } })
            @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
        </div>
    </div>

    <label for="file">Image</label>
    <div class="input-group mb-3">
        <div class="input-group-prepend">
            <span class="input-group-text" id="inputGroupFileAddon01">Upload</span>
        </div>
        <div class="custom-file">
            <input type="file" class="custom-file-input" id="file" name="file" aria-describedby="inputGroupFileAddon01">
            <label class="custom-file-label" for="file">Choose file</label>
        </div>
    </div>

}

@section scripts {
    <script src="/Scripts/bs-custom-file-input.min.js"></script>
    <script>
        $(document).ready(function () {
            bsCustomFileInput.init()
        })
    </script>
}

BikeMgr.Web/Views/Bike/Edit.cshtml
@model BikeMgrWeb.Models.BikeDetailView

@{
    ViewBag.Title = "Create a Bike";
    Layout = "~/Views/Shared/_LayoutDialog.cshtml";
}

<h2 class="mt-3">Create a Bike</h2>

@using (Html.BeginForm("Edit", "Bike", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="row">
        <div class="col-md-3">
            <input type="submit" value="Save" class="btn btn-primary mb-2" />
            <a href="~/Bike/Details/@Model.ID" class="btn btn-secondary mb-2">Cancel</a>
        </div>
        <div class="col-md-7">
            <a href="~/Bike" class="btn btn-info">Back To List</a>
        </div>
        <div class="col-md-2">
            <button type="button" class="btn btn-danger float-right" data-toggle="modal" data-target="#modDelete">Delete</button>
        </div>
    </div>

    if (!String.IsNullOrWhiteSpace(ViewBag.FileResult))
    {
        <div class="alert alert-danger" role="alert">
            @ViewBag.FileResult
        </div>
    }

    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <input hidden id="ID" name="ID" value="@Model.ID" />

    <div class="form-row mt-2">
        <div class="form-group col">
            @Html.LabelFor(model => model.Name)
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", @aria_label = "Model Name" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
        <div class="form-group col">
            @Html.LabelFor(model => model.Brand)
            @Html.EditorFor(model => model.Brand, new { htmlAttributes = new { @class = "form-control", @aria_label = "Brand" } })
            @Html.ValidationMessageFor(model => model.Brand, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-row">
        <div class="form-group col-md-2">
            @Html.LabelFor(model => model.Wheels)
            @Html.EditorFor(model => model.Wheels, new { htmlAttributes = new { @class = "form-control", @aria_label = "Number of wheels" } })
            @Html.ValidationMessageFor(model => model.Wheels, "", new { @class = "text-danger" })
        </div>
        <div class="form-group col-md-3">
            @Html.LabelFor(model => model.FrameMaterial)
            @Html.EditorFor(model => model.FrameMaterial, new { htmlAttributes = new { @class = "form-control", @aria_label = "Frame Material" } })
            @Html.ValidationMessageFor(model => model.FrameMaterial, "", new { @class = "text-danger" })
        </div>
        <div class="form-group col-md-3">
            @Html.LabelFor(model => model.BikeType)
            @Html.DropDownList("BikeType.ID", (IEnumerable<SelectListItem>)Model.BikeTypes, "Choose...", htmlAttributes: new { @class = "form-control", @required = "true", @aria_label = "Bike Type" })
            @Html.ValidationMessageFor(model => model.BikeType, "", new { @class = "text-danger" })
        </div>
        <div class="form-group col-md-2">
            @Html.LabelFor(model => model.Price)
            @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control", @aria_label = "Price" } })
            @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
        </div>
    </div>

    <label for="file">Image</label>
    <div class="input-group mb-3">
        <div class="input-group-prepend">
            <span class="input-group-text" id="inputGroupFileAddon01">Upload</span>
        </div>
        <div class="custom-file">
            <input type="file" class="custom-file-input" id="file" name="file" aria-describedby="inputGroupFileAddon01">
            <label class="custom-file-label" for="file">Choose file</label>
        </div>
    </div>

    <div class="form-row">
        @{
            if (Model.ImageLocation != null)
            {
                <img src="@Model.ImageLocation" class="img-fluid" alt="Responsive image">
                <input hidden id="ImageLocation" name="ImageLocation" value="@Model.ImageLocation" />
            }
            else
            {
                <label>No image on file</label>
            }
        }
    </div>

}

@Html.Partial("_BikeDeleteDialog")

@section scripts {
    <script src="/Scripts/bs-custom-file-input.min.js"></script>
    <script>
    $(document).ready(function () {
        bsCustomFileInput.init()
    })
    </script>
}

BikeMgr.Web/Views/Bike/Index.cshtml
@using BikeMgrWeb.Models;
@model BikeMgrWeb.Models.BikeIndexView<BikeMgrWeb.Models.Bike>
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
    ViewBag.Title = "Bike List";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 class="mt-3">Bike List</h2>
@if (@ViewBag.AlertMsg != null)
{
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
        @ViewBag.AlertMsg
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
}

<div class="btn-toolbar justify-content-between" role="toolbar" aria-label="Toolbar with list options">

    @if (User.Identity.HasPermission("write"))
    {
        <div class="btn-group" role="group" aria-label="First group">
            <a href="../Bike/Create" class="btn btn-primary mb-2">Create New</a>
        </div>
    }
    <div class="input-group">
        @using (Html.BeginForm("Index", "Bike", FormMethod.Get, new { @class = "form-inline my-2 my-lg-0 mr-2" }))
        {
            <input id="sortOrder" name="sortOrder" type="hidden" placeholder="sortOrder" value="@Model.CurrentSort" />
            <span>Name/Brand:&nbsp;</span>
            <input id="search" name="search" class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" value="@Model.CurrentFilter">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        }
    </div>
</div>

<table class="table table-hover">
    <thead class="thead-dark">
        <tr>
            <th>
                @Html.ActionLink("Model Name", "Index", new { sortOrder = Model.NameSort, currentFilter = Model.CurrentFilter, page = Model.PageNo }, new { @class = "column-header-a" })
            </th>
            <th>
                @Html.ActionLink("Brand", "Index", new { sortOrder = Model.BrandSort, currentFilter = Model.CurrentFilter, page = Model.PageNo }, new { @class = "column-header-a" })
            </th>
            <th>
                @Html.ActionLink("No of wheels", "Index", new { sortOrder = Model.WheelSort, currentFilter = Model.CurrentFilter, page = Model.PageNo }, new { @class = "column-header-a" })
            </th>
            <th>
                @Html.ActionLink("Frame Material", "Index", new { sortOrder = Model.FrameSort, currentFilter = Model.CurrentFilter, page = Model.PageNo }, new { @class = "column-header-a" })
            </th>
            <th>
                @Html.ActionLink("Type", "Index", new { sortOrder = Model.TypeSort, currentFilter = Model.CurrentFilter, page = Model.PageNo }, new { @class = "column-header-a" })
            </th>
            <th>
                @Html.ActionLink("Price", "Index", new { sortOrder = Model.PriceSort, currentFilter = Model.CurrentFilter, page = Model.PageNo }, new { @class = "column-header-a" })
            </th>
            <th></th>
        </tr>
    </thead>

    @foreach (var item in Model.Items)
    {
<tr>
    <td data-href="../Bike/Details/@item.ID">
        @Html.DisplayFor(modelItem => item.Name)
    </td>
    <td data-href="../Bike/Details/@item.ID">
        @Html.DisplayFor(modelItem => item.Brand)
    </td>
    <td data-href="../Bike/Details/@item.ID">
        @Html.DisplayFor(modelItem => item.Wheels)
    </td>
    <td data-href="../Bike/Details/@item.ID">
        @Html.DisplayFor(modelItem => item.FrameMaterial)
    </td>
    <td data-href="../Bike/Details/@item.ID">
        @Html.DisplayFor(modelItem => item.BikeType.TypeName)
    </td>
    <td data-href="../Bike/Details/@item.ID">
        @Html.DisplayFor(modelItem => item.Price)
    </td>
    <td>
        <a href="../Bike/Edit/@item.ID" class="fa fa-edit"></a>
        @Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
        <a href="#" class="fa fa-trash-o" data-toggle="modal" data-target="#modDelete" data-id="@(item.ID)" data-name="@item.Name"></a>
        <a href="#" data-toggle="modal" data-target="#modDelete" data-id="@(item.ID)" data-name="@item.Name">Delete</a>
    </td>
</tr>
    }

</table>

<div class="modal fade" id="modDelete" tabindex="-1" role="dialog" aria-labelledby="Delete Dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Delete Bike</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div id="modDeleteBody" class="modal-body">
                Are you sure you want to delete the ..Name.. bike?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <a id="modDeleteAnchor" href="../Bike/Delete/" class="btn btn-primary">Delete</a>
            </div>
        </div>
    </div>
</div>

@{
    var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
    var nextDisabled = !Model.HasNextPage ? "disabled" : "";
}
<nav aria-label="Page navigation">
    <ul class="pagination">
        <li class="page-item @prevDisabled">
            <a class="page-link" href="../Bike/Index?page=1&sortOrder=@Model.CurrentSort&currentFilter=@Model.CurrentFilter" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
            </a>
        </li>
        <li class="page-item @prevDisabled">
            <a class="page-link" href="../Bike/Index?page=@(Model.PageNo-1)&sortOrder=@Model.CurrentSort&currentFilter=@Model.CurrentFilter" aria-label="Previous">
                <span aria-hidden="true">&#8249;</span>
            </a>
        </li>
        @{
            int pageOffset = Model.PageNo - 2 < 1 ? 1 : Model.PageNo - 2;
            if (Model.PageNo > Model.TotalPages - 2 && Model.TotalPages > 4)
            {
                pageOffset = Model.TotalPages - 5 + Model.TotalPages - Model.PageNo;
                if (Model.PageNo == Model.TotalPages) { pageOffset = Model.TotalPages - 4; }
            }
            if (pageOffset == 0) { pageOffset = 1; }
            int pageCounter = 1;
            while (pageCounter <= 5 && pageOffset <= Model.TotalPages)
            {
                if (pageOffset == @Model.PageNo)
                {
                    <li class="page-item active" aria-current="page">
                        <a class="page-link" href="#">@Model.PageNo<span class="sr-only">(current)</span></a>
                    </li>
                }
                else
                {
                    <li class="page-item"><a class="page-link" href="../Bike/Index?page=@pageOffset&sortOrder=@Model.CurrentSort&currentFilter=@Model.CurrentFilter">@pageOffset</a></li>
                }
                pageCounter++;
                pageOffset++;
            }
        }
        <li class="page-item @nextDisabled">
            <a class="page-link" href="../Bike/Index?page=@(Model.PageNo+1)&sortOrder=@Model.CurrentSort&currentFilter=@Model.CurrentFilter" aria-label="Next">
                <span aria-hidden="true">&#8250;</span>
            </a>
        </li>
        <li class="page-item @nextDisabled">
            <a class="page-link" href="../Bike/Index?page=@Model.TotalPages&sortOrder=@Model.CurrentSort&currentFilter=@Model.CurrentFilter" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
            </a>
        </li>
    </ul>
</nav>
Page @Model.PageNo of @Model.TotalPages

@section scripts {
    <script>
        jQuery(document).ready(function ($) {
            $('*[data-href]').on('click', function () {
                window.location = $(this).data("href");
            });
        });

        $('#modDelete').on('show.bs.modal', function (event) {
            var button = $(event.relatedTarget)
            $(this).find('#modDeleteBody').text('Are you sure you want to delete the ' + button.data('name') + ' bike?')
            $(this).find('#modDeleteAnchor').attr('href', '/Bike/Delete/' + button.data('id'));
        })
    </script>
}